# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Arena stats

Resources:
    BuildHourlyArenaClassStats:
        Type: AWS::Serverless::Function
        Properties:
            Handler: hourly/_build-hourly-arena-class-stats.default
            Runtime: nodejs18.x
            Timeout: 880
            CodeUri: ./dist/hourly/_build-hourly-arena-class-stats
            MemorySize: 2000
            ReservedConcurrentExecutions: 5
            # Layers:
            #     - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                - AmazonS3FullAccess
                - AWSLambda_FullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                # - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: cron-build-hourly-arena-class-stats
            Events:
                LastPeriodTrigger:
                    Type: Schedule
                    Properties:
                        Schedule: cron(15 * * * ? *)
    BuildDailyAggregateStats:
        Type: AWS::Serverless::Function
        Properties:
            Handler: daily/_build-daily-aggregate.default
            Runtime: nodejs18.x
            Timeout: 880
            CodeUri: ./dist/daily/_build-daily-aggregate
            MemorySize: 4000
            ReservedConcurrentExecutions: 5
            # Layers:
            #     - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                - AmazonS3FullAccess
                - AWSLambda_FullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: cron-build-daily-arena-aggregate-stats
            Events:
                LastPeriodTrigger:
                    Type: Schedule
                    Properties:
                        Schedule: cron(0 5 * * ? *)
    FinalStats:
        Type: AWS::Serverless::Function
        Properties:
            Handler: final-stats/_build-final-stats.default
            Runtime: nodejs18.x
            Timeout: 880
            CodeUri: ./dist/final-stats/_build-final-stats
            MemorySize: 1000
            ReservedConcurrentExecutions: 5
            # Layers:
            #     - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
                - AmazonS3FullAccess
                - AWSLambda_FullAccess
                - arn:aws:iam::aws:policy/CloudWatchLambdaInsightsExecutionRolePolicy
                - arn:aws:iam::478062583808:policy/CloudWatchPolicyForLambda # See https://stackoverflow.com/questions/51166504/disable-cloudwatch-to-monitor-logs-for-lambda-function
            Tags:
                LambdaName: cron-arena-final-stats
            Events:
                LastPeriodTrigger:
                    Type: Schedule
                    Properties:
                        # Cron that runs every hour at 25 minutes past the hour
                        Schedule: cron(25 * * * ? *)
